In [87]:
import spcm
from spcm import units
import numpy as np
from atommover.utils import Move


def shape_linear(x):
    return x

def shape_cosine(x):
    return 0.5-0.5*np.cos(np.pi*x)

def shape_square(x):
    return np.where(x < 0.5, 0, 1)

def shape_three_order_polynomial(x):    
    return 3*x**2 - 2*x**3  


class Serial_AOD_2D_DDS():
    def __init__(self, card: spcm.Card, core_number_x: int, core_number_y: int, f_list_x: np.ndarray, f_list_y: np.ndarray):
        self.card = card
        self.core_number_x = core_number_x
        self.core_number_y = core_number_y
        self.f_list_x = f_list_x
        self.f_list_y = f_list_y
        self.core_list_x = []
        self.core_list_y = []
        self.dds = None 
        self.allocate_cores()
        self.card_setup()   
    def allocate_cores(self):
        cores_y_available = [
            spcm.SPCM_DDS_CORE8, spcm.SPCM_DDS_CORE9, spcm.SPCM_DDS_CORE10, 
            spcm.SPCM_DDS_CORE11, spcm.SPCM_DDS_CORE20
        ]
        self.core_list_y = cores_y_available[-self.core_number_y:]
        print(self.core_list_y)
        print(len(self.core_list_y))
        cores_x_available = [
            spcm.SPCM_DDS_CORE0, spcm.SPCM_DDS_CORE1, spcm.SPCM_DDS_CORE2,                      
            spcm.SPCM_DDS_CORE3, spcm.SPCM_DDS_CORE4, spcm.SPCM_DDS_CORE5,      
            spcm.SPCM_DDS_CORE6, spcm.SPCM_DDS_CORE7, spcm.SPCM_DDS_CORE12, 
            spcm.SPCM_DDS_CORE13, spcm.SPCM_DDS_CORE14, spcm.SPCM_DDS_CORE15,
            spcm.SPCM_DDS_CORE16, spcm.SPCM_DDS_CORE17, spcm.SPCM_DDS_CORE18,
            spcm.SPCM_DDS_CORE19
        ]
        self.core_list_x = cores_x_available[0:self.core_number_x]
    def card_setup(self):
        self.card.card_mode(spcm.SPC_REP_STD_DDS)
        channels = spcm.Channels(self.card)
        channels.enable(True)
        channels.output_load(50 * units.ohm)
        channels.amp(1 * units.V)
        self.card.write_setup() # IMPORTANT! this turns on the card's system clock signals, that are required for DDS to work
        
        self.dds = spcm.DDS(self.card, channels=channels)
        self.dds.reset()
        self.dds.cores_on_channel(1,*self.core_list_y)

        self.dds.freq_ramp_stepsize(1000)      #Tune the number of steps for frequency ramping 
        self.dds.trg_timer(5.0 * units.s)      #Set a waiting time for rearrangement
        self.dds.trg_src(spcm.SPCM_DDS_TRG_SRC_TIMER)

    def single_movement(self,DDS_core_list,freq_init_list:np.ndarray, freq_final_list:np.ndarray, duration, num_segments, shape):
        print("Moving from", freq_init_list, "to", freq_final_list)
        frequency_range_list = freq_final_list - freq_init_list
        unit_slices_in = np.linspace(0, 1, num_segments+1, endpoint=True)
        unit_slices_out = np.array(shape(unit_slices_in))
        # time_list = unit_slices_in*duration
        output_list = np.outer(frequency_range_list.magnitude, unit_slices_out) 
        # t_diff = np.diff(time_list)     duration_segment may not be a constant
        y_diff = np.diff(output_list)
        duration_segment = duration / num_segments 
        print("Duration per segment:", duration_segment)
        for j in range(len(DDS_core_list)):  # Initialize frequencies, amplitudes and phases    
            DDS_core_list[j].frequency(freq_init_list[j])
            DDS_core_list[j].amp(45 * units.percent / 20) #???
            DDS_core_list[j].phase(180*np.random.rand()*units.degrees)
        self.dds.exec_at_trg()
        self.dds.write_to_card()

           # Ramp the shape
        for i in range(num_segments):
            self.dds.trg_timer(duration_segment)
            for j in range(len(DDS_core_list)):
                DDS_core_list[j].frequency_slope(y_diff[j][i]*units.MHz /duration_segment) 
            self.dds.exec_at_trg()
            # self.dds.write_to_card()   

        for j in range(len(DDS_core_list)):
            DDS_core_list[j].frequency_slope(0) # Stop frequency ramping, may be later also amplitude shut down??
            DDS_core_list[j].freq(freq_final_list[j])
            DDS_core_list[j].phase(180*np.random.rand()*units.degrees)
        self.dds.exec_at_trg()
        self.dds.write_to_card()

    def single_movement_batch(self,DDS_core_list_x,DDS_core_list_y,freq_init_list_x:np.ndarray, freq_final_list_x:np.ndarray, freq_init_list_y:np.ndarray, freq_final_list_y:np.ndarray, duration, num_segments, shape):
        # print("Moving from", freq_init_list, "to", freq_final_list)
        print("Moving from", freq_init_list_x, freq_init_list_y, "to", freq_final_list_x, freq_final_list_y)                                    
        frequency_range_list_x = freq_final_list_x - freq_init_list_x
        frequency_range_list_y = freq_final_list_y - freq_init_list_y   
        unit_slices_in = np.linspace(0, 1, num_segments+1, endpoint=True)
        unit_slices_out = np.array(shape(unit_slices_in))
        # time_list = unit_slices_in*duration
        output_list_x = np.outer(frequency_range_list_x.magnitude, unit_slices_out)
        output_list_y = np.outer(frequency_range_list_y.magnitude, unit_slices_out)
        # t_diff = np.diff(time_list)     duration_segment may not be a constant
        x_diff = np.diff(output_list_x)
        y_diff = np.diff(output_list_y)
        duration_segment = duration / num_segments
        print("Duration per segment:", duration_segment)
        STEP = len(freq_init_list_x)  #the four freq listhould all equal
        print(STEP)
        for j in range(STEP):  # Initialize frequencies, amplitudes and phases    
            DDS_core_list_x[j].frequency(freq_init_list_x[j])
            DDS_core_list_x[j].amp(45 * units.percent / 20) #???
            DDS_core_list_x[j].phase(180*np.random.rand()*units.degrees)
            DDS_core_list_y[j].frequency(freq_init_list_y[j])
            DDS_core_list_y[j].amp(45 * units.percent / 20) #???        
            DDS_core_list_y[j].phase(180*np.random.rand()*units.degrees)
        self.dds.exec_at_trg()
        self.dds.write_to_card()

           # Ramp the shape
        for i in range(num_segments):
            self.dds.trg_timer(duration_segment)
            for j in range(STEP):
                DDS_core_list_x[j].frequency_slope(x_diff[j][i]*units.MHz /duration_segment) 
                DDS_core_list_y[j].frequency_slope(y_diff[j][i]*units.MHz /duration_segment)
            self.dds.exec_at_trg()
            # self.dds.write_to_card()   

        for j in range(STEP):
            DDS_core_list_x[j].frequency_slope(0) # Stop frequency ramping, may be later also amplitude shut down??
            DDS_core_list_x[j].freq(freq_final_list_x[j])
            DDS_core_list_x[j].phase(180*np.random.rand()*units.degrees)
            DDS_core_list_x[j].amp(0)
            DDS_core_list_y[j].frequency_slope(0) # Stop frequency ramping, may be later also amplitude shut down??
            DDS_core_list_y[j].freq(freq_final_list_y[j])
            DDS_core_list_y[j].phase(180*np.random.rand()*units.degrees)
            DDS_core_list_y[j].amp(0)
        self.dds.exec_at_trg()
        self.dds.write_to_card()

    def wait(self):
        self.card.start(spcm.M2CMD_CARD_ENABLETRIGGER, spcm.M2CMD_CARD_FORCETRIGGER)
        input("Press Enter to Exit")

    def rearrange(self,move_sequence: list[Move]):
        
        for move in move_sequence:
            freq_x_init = self.f_list_x[move[0].from_row]
            freq_y_init = self.f_list_y[move[0].from_col]
            freq_x_final = self.f_list_x[move[0].to_row]
            freq_y_final = self.f_list_y[move[0].to_col]
            self.single_movement(
                [self.dds[0], self.dds[8]],   # Currently only one core in each direction, one finger kungfu
                np.array([freq_x_init, freq_y_init])*units.MHz,
                np.array([freq_x_final, freq_y_final])*units.MHz,
                10*units.s,
                10,
                shape_three_order_polynomial
            )
    def parrallel_rearrange(self, move_sequence: list[Move]):
        for move in move_sequence:
            freq_x_init = [self.f_list_x[m.from_row] for m in move]
            freq_y_init = [self.f_list_y[m.from_col] for m in move]
            freq_x_final = [self.f_list_x[m.to_row] for m in move]
            freq_y_final = [self.f_list_y[m.to_col] for m in move]
            self.single_movement_batch(
                self.dds[0:4],self.dds[8:12],   # Currently only one core in each direction, one finger kungfu
                np.array(freq_x_init)*units.MHz,np.array(freq_x_final)*units.MHz,
                np.array(freq_y_init)*units.MHz,np.array(freq_y_final)*units.MHz,
                10*units.s,
                10,
                shape_three_order_polynomial
            )                                           

In [57]:
import numpy as np
import copy
import time
from collections import deque
from scipy.optimize import linear_sum_assignment
from scipy.sparse import csr_matrix
from atommover.utils.move_utils import Move
from atommover.utils.AtomArray import AtomArray
from atommover.algorithms.Algorithm_class import Algorithm
def generate_cost_matrix(current_positions, target_positions):
    num_atoms = len(current_positions)
    num_targets = len(target_positions)
    cost_matrix = np.zeros((num_atoms, num_targets))

    for i, current in enumerate(current_positions):
        for j, target in enumerate(target_positions):
            cost_matrix[i, j] = np.sqrt((current[0] - target[0])**2 + (current[1] - target[1])**2)
    return cost_matrix
def move_atom_and_show_grid(grid, start, end):
    #Initialize current position
    current_pos = start
    path = []
    
    while current_pos != end:
        path, current_pos = bfs_move_atom(grid, current_pos, end, path)
        
    path = flatten_tuple(path)[::-1]
    grid, path = generate_decomposed_move_set(grid, path)

    return path
def bfs_move_atom(grid, start, end, prev_path):
    queue = deque([(start[0], start[1], [(start[0], start[1])])]) #Use the queue to record current position and path
    visited = set() #Record the visited positions
    visited.add((start[0], start[1]))

    #Start finding the path
    while queue:
        current_row, current_col, path = queue.popleft() #Update current position

        #If we arrive end point, return the path
        if (current_row, current_col) == end:
            if len(prev_path) > 0:
                prev_path = prev_path, path
            else:
                prev_path = path

            return prev_path, end

        #Explore the next step (based on current position and end point)
        len_path = len(path) - 1
        dr = 1 if end[0] > path[len_path][0] else (-1 if end[0] < path[len_path][0] else 0) 
        dc = 1 if end[1] > path[len_path][1] else (-1 if end[1] < path[len_path][1] else 0)
        new_row, new_col = current_row + dr, current_col + dc

        #Check if there is an obstacle there (If no, start from this new point to find next step)
        if (new_row, new_col) not in visited and grid[new_row][new_col] == 0:
            visited.add((new_row, new_col))
            queue.append((new_row, new_col, path + [(new_row, new_col)])) 

    #If there is an obstacle on the path, we decompose the path: start->obstacle->target
    #Define the obstacle position
    obstacle = (path[len_path][0] + dr, path[len_path][1] + dc)

    # Update the move in path until obstacle
    if len(prev_path) > 0:
        prev_path = prev_path, path + [obstacle]
    else:
        prev_path = path + [obstacle]

    #[Path between start and obstacle] + [Path between obstacle and end]
    return prev_path, obstacle
def flatten_tuple(nested_tuple):
    # This function will flatten a nested tuple of lists into a single tuple of lists
    result = []
    
    def recursive_flatten(element):
        if isinstance(element, tuple):
            # If the element is a tuple, apply recursion to each item
            for item in element:
                recursive_flatten(item)
        elif isinstance(element, list):
            # If the element is a list, append it to the result
            result.append(tuple(element))

    # Start the recursion with the entire nested tuple
    recursive_flatten(nested_tuple)
    
    # Convert the list of tuples into a single tuple
    return tuple(result)
def generate_decomposed_move_set(grid, path):
    decomposed_move_set = []

    #Iterate all path segments (((a1,b1), (a2,b2), (a3, b3), (a4,b4)), ((c1,d1), (c2,d2)))
    try:
        for segmant in path:
            from_row, from_col = segmant[0]
            for coordinate in segmant:
                to_row, to_col = coordinate
                # To exclude the frist move
                if from_row != to_row or from_col != to_col:
                    decomposed_move_set.append([Move(from_row, from_col, to_row, to_col)])
                    grid[from_row][from_col] = 0
                    grid[to_row][to_col] = 1
                    from_row, from_col = to_row, to_col
            # decomposed_move_set.append(segmant_moves)
    except IndexError:
        return grid, []
        
    return grid, decomposed_move_set
def define_current_and_target(matrix, target_config):
    current_positions = [(x, y) for x in range(len(matrix[0])) for y in range(len(matrix)) if matrix[x][y] == 1 if target_config[x][y] == 0] #NKH this should in theory not change anything...
    target_positions = [(x, y) for x in range(len(matrix[0])) for y in range(len(matrix)) if target_config[x][y] == 1 if matrix[x][y] == 0] #same here
    return current_positions, target_positions
def generate_cost_matrix_scipy(current_positions, target_positions):
    # current_positions, target_positions: sequence of (x,y) pairs
    if len(current_positions) == 0 or len(target_positions) == 0:
        return np.zeros((len(current_positions), len(target_positions)))
    A = np.asarray(current_positions, dtype=float)
    B = np.asarray(target_positions, dtype=float)
    from scipy.spatial.distance import cdist
    return cdist(A, B, metric='euclidean')


In [92]:
import time
from atommover.utils import PhysicalParams
from atommover.utils import AtomArray      
from atommover.algorithms import Hungarian
from atommover.algorithms.source.Hungarian_works import Hungarian_algorithm_works   
from atommover.algorithms.source.Hungarian_works import parallel_Hungarian_algorithm_works
# Start timing
start_time = time.time()

# specifying parameters
load_prob = 0.7 # float; the probability that an individual site will be loaded
array_length = 10 # int; number of rows (or cols) of the square array

params = PhysicalParams(loading_prob = load_prob)

# Time array initialization
init_start = time.time()
atom_array_1 = AtomArray([array_length, array_length], 1, params)
init_time = time.time() - init_start
print(f"Array initialization time: {init_time:.4f} seconds")

# Time tweezer loading
load_start = time.time()
atom_array_1.load_tweezers()
load_time = time.time() - load_start
print(f"Tweezer loading time: {load_time:.4f} seconds")

# Time target generation
target_start = time.time()
atom_array_1.generate_target()
target_time = time.time() - target_start
print(f"Target generation time: {target_time:.4f} seconds")

# Time visualization
viz_start = time.time()
# atom_array_1.image()
# atom_array_1.plot_target_config()
viz_time = time.time() - viz_start
print(f"Visualization time: {viz_time:.4f} seconds")

# Time algorithm
algo_start = time.time()
algo1 = Hungarian()  
algo_init_time = time.time() - algo_start
print(f"Algorithm initialization time: {algo_init_time:.4f} seconds")

# Time move calculation
moves_start = time.time()
# move_sequence = Hungarian_algorithm_works(atom_array_1.matrix[:,:,0], atom_array_1.target)[1]                           
move_sequence = parallel_Hungarian_algorithm_works(atom_array_1.matrix[:,:,0], atom_array_1.target)[1]
moves_time = time.time() - moves_start
print(f"Move sequence calculation time: {moves_time:.4f} seconds")

# Total time
total_time = time.time() - start_time
print(f"\nTotal execution time: {total_time:.4f} seconds")
print(f"Number of moves: {len(move_sequence) if move_sequence else 0}")
print(move_sequence)
print(move_sequence[1][0].from_row)

Array initialization time: 0.0002 seconds
Tweezer loading time: 0.0003 seconds
Target generation time: 0.0002 seconds
Visualization time: 0.0001 seconds
Algorithm initialization time: 0.0001 seconds
Mismatch in shapes (10, 10) and (10, 10, 1). Reshaping.
Mismatch in shapes (10, 10) and (10, 10, 1). Reshaping.
Mismatch in shapes (10, 10) and (10, 10, 1). Reshaping.
Mismatch in shapes (10, 10) and (10, 10, 1). Reshaping.
Mismatch in shapes (10, 10) and (10, 10, 1). Reshaping.
Mismatch in shapes (10, 10) and (10, 10, 1). Reshaping.
Mismatch in shapes (10, 10) and (10, 10, 1). Reshaping.
Mismatch in shapes (10, 10) and (10, 10, 1). Reshaping.
Mismatch in shapes (10, 10) and (10, 10, 1). Reshaping.
Mismatch in shapes (10, 10) and (10, 10, 1). Reshaping.
Mismatch in shapes (10, 10) and (10, 10, 1). Reshaping.
Mismatch in shapes (10, 10) and (10, 10, 1). Reshaping.
Mismatch in shapes (10, 10) and (10, 10, 1). Reshaping.
Mismatch in shapes (10, 10) and (10, 10, 1). Reshaping.
Mismatch in shape

In [93]:
import spcm
from spcm import units

card : spcm.Card #Init card
with spcm.Card('/dev/spcm0') as card: 
    # instance0 = Serial_AOD_2D_DDS(card, 5, 5, np.linspace(99,101,11), np.linspace(99,101,11))               
    # instance0.rearrange(move_sequence)    
    # instance0.wait()
    instance1 = Serial_AOD_2D_DDS(card, 5, 5, np.linspace(99,101,11), np.linspace(99,101,11))
    instance1.parrallel_rearrange(move_sequence)     
    instance1.wait()


[256, 512, 1024, 2048, 1048576]
5
Moving from [99.2 99.6 100.8 100.4] MHz [100.0 100.0 99.6 100.0] MHz to [99.2 99.6 100.6 100.6] MHz [100.2 100.2 99.6 100.2] MHz
Duration per segment: 1.0 s
4
Moving from [99.0 99.4 100.2] MHz [100.6 100.2 99.0] MHz to [99.2 99.4 100.4] MHz [100.6 100.0 99.0] MHz
Duration per segment: 1.0 s
3
Moving from [99.6 99.6] MHz [99.6 100.8] MHz to [99.8 99.8] MHz [99.6 100.8] MHz
Duration per segment: 1.0 s
2
Moving from [99.8] MHz [99.8] MHz to [99.8] MHz [100.0] MHz
Duration per segment: 1.0 s
1
Moving from [99.8 99.8] MHz [99.4 100.6] MHz to [100.0 100.0] MHz [99.6 100.8] MHz
Duration per segment: 1.0 s
2
Moving from [100.0 100.0] MHz [99.6 100.8] MHz to [100.2 100.2] MHz [99.6 100.8] MHz
Duration per segment: 1.0 s
2
Moving from [100.6] MHz [100.2] MHz to [100.8] MHz [100.2] MHz
Duration per segment: 1.0 s
1


In [13]:
import numpy as np
a = np.array([1,2,3])   
b = np.array([4,5,6])   
output = np.outer(a,b)
print(output)   

d = b*units.MHz 
print(d)
print(d.magnitude)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[4 5 6] MHz
[4 5 6]
